getlidar/helika-web-sdk

- README.md
- dist/game/index.d.ts
- dist/game/index.js
- example/package.json
- example/src/components/ApiForm.tsx
- package.json
- src/game/index.ts
In this PR:
- updated modifyScore function to take in array of users
> Bulkmodify

- dist/game/index.d.ts
- dist/game/index.js
- example/package.json
- package.json
- src/game/index.ts
> Fix logclick

- dist/game/index.d.ts
- dist/game/index.js
- package.json
- src/game/index.ts
In this PR:
- created a function for trigger custom game events
> triggerEvent

- package-lock.json
> run npm install

- README.md
- package-lock.json
- package.json
> update helika-ua-sdk to helika-sdk in readme

- dist/base.d.ts
- dist/base.js
- dist/index.d.ts
- dist/index.js
- package-lock.json
- package.json
- src/base.ts
- src/index.ts
In this PR:
- move away from dynamic import
> move away from dynamic import

- dist/base.js
- package.json
- src/base.ts
In this PR:
- pass null fingerprint data if unavailable, so that events still sent
> pass null fingerprint data if unavailable

- dist/index.d.ts
- dist/index.js
- src/index.ts
In this PR:
- remove mixing logic
> remove mixin

- dist/base.d.ts
- dist/base.js
- dist/events/index.d.ts
- dist/events/index.js
- package-lock.json
- package.json
- src/base.ts
- src/events/index.ts
- yarn.lock
In this PR:
- account for SSR
- session ID null on sdk instantiation
- startSession function that initialized instance with session ID and sends session create event to api
- event functions will throw error if no session
> apply changes to account for ssr, create startSession function

- dist/base.d.ts
- dist/base.js
- dist/events/index.js
- package.json
- src/base.ts
- src/events/index.ts
In this PR:
- add expiry date to sdk instance
- if expired, don't fingerprint
> add expiry, dont fingerprint if expired

- dist/base.js
- src/base.ts
In this PR:
- apply cloud front proxy
> use cloudfront proxy to get around adblocker

- README.md
- src/events/index.ts
In this PR:
- Updated Readme to remove UA docs. 
- Removed unused param from Events API
> Updated Readme

- src/base.ts
- src/events/index.ts
In this PR:
- remove fingerprint from events, add extend expiry function
> remove fingerprint from events, add exend expiry

- README.md
- dist/base.d.ts
- dist/base.js
- dist/events/index.d.ts
- dist/events/index.js
- package-lock.json
- package.json
- src/base.ts
- src/events/index.ts
- yarn.lock
In this PR:
- account for SSR
- session ID null on sdk instantiation
- startSession function that initialized instance with session ID and
sends session create event to api
- event functions will throw error if no session
- add session expiry and session refresh
- use local storage for utms and referral link, move to session create/refresh
- use cloud front proxy
- remove fingerprinting from events create
- add internal extend session function
> Release 10/27

- dist/base.d.ts
- dist/base.js
- dist/events/index.d.ts
- dist/events/index.js
- package.json
- src/base.ts
IN this PR:
- check for session id in session start
> Ps/bugfix/session start localstorage (#45)

- README.md
- package.json
- src/base.ts
- src/events/index.ts
In this PR:
- update some console.logs() into console.error()
- UTMs are stored incorrectly in localStorage. it shows `[Object]: [object]` which in turn, doesn't send utms correctly when an event sent along with game events
> UTMs incorrectly stored in localStorage

- README.md
- dist/base.js
- dist/events/index.js
- package.json
- src/base.ts
In this PR:
- update npm version and fix version in fp call
> update npm version and fix version in fp call

- README.md
- dist/base.d.ts
- dist/base.js
- dist/index.d.ts
- dist/index.js
- package.json
- src/base.ts
- src/index.ts
- yarn.lock
In this PR:
- Added enum to disables specific fingerprint info from getting stored
> Release v.0.2.1

- package.json
- src/base.ts
In this PR:
- Only call fingerprint on new session create
> Move fingerprint to occur only on new session

- .github/workflows/main.yml
> Ps/feature/cicd (#56)

- package.json
- src/base.ts
In this PR:
- add session create subtype
> add session create sub_type

- src/base.ts
- src/events/index.ts
In this PR:
- turn sessionID into session_id when sent to helika_api
> turn sessionID into session_id when sent to helika_api

- package.json
- src/base.ts
- src/events/index.ts
In this PR:
- add session create subtype
> add session create sub_type (#62)

- src/events/index.ts
In this PR:
- fix error message for no session id
> Fix error message

- src/base.ts
- src/events/index.ts
- src/index.ts
- src/utils.ts
In this PR:
- Reorganized public, protected, and private functions
- Cleaned up event creation
- removed unused code
> Optimizations

- package-lock.json
- package.json
- src/base.ts
- src/index.ts
- yarn.lock
In this PR:
- removed fingerprintjs
> Deprecate Fingerprint

- README.md
- src/base.ts
- src/events/index.ts
- src/index.ts
- yarn.lock
In this PR:
- Enable/Disable Personal Identifiable Information Tracking
- Add Referral Data
- Fixed where sdk data is supposed to go
- Fixed sessionId null bug
- Only append user_details if it's a user event
> Add PII Tracking, Add Referral Data to event, small bugs

- src/base.ts
In this PR:
- return utms to session create
> add back session create
